# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
- pre-commit
- commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
        args: [--fix=no]
    -   id: no-commit-to-branch
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8

-   repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
    -   id: shellcheck
    -   id: shfmt

-   repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh

# -   repo: https://github.com/compilerla/conventional-pre-commit
#     rev: v2.4.0
#     hooks:
#     -   id: conventional-pre-commit
#         stages: [commit-msg]
#         args: []

# -   repo: https://github.com/commitizen-tools/commitizen
#     rev: 3.12.0
#     hooks:
#     -   id: commitizen
    # -   id: commitizen-branch
