# =============================================================================
# dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
# =============================================================================

[options]
automatic_update = true
statusline_iseparator = 'arrow'
statusline_separator = 'arrow'
# disable 'q' to close current window
# windows_smartclose = ''
# in vimcompatible mode, all the differences above will disappear
vimcompatible = true
buffer_index_type = 4
colorscheme = 'gruvbox'
colorscheme_bg = 'dark'
default_indent = 4
disabled_plugins = ['tagbar']
enable_guicolors = true
enable_statusline_mode = true
enable_tabline_filetype_icon = true
filemanager = 'nerdtree'
guifont = 'AgaveNF-Regular:h15'

# ~/.SpaceVim.d/autoload/myspacevim.vim
bootstrap_after = 'myspacevim#after'
bootstrap_before = 'myspacevim#before'

# options for non-project files/directories
project_non_root = 'current'
# project_rooter_patterns = ['.git/', '!node_packages/']
# project_rooter_outermost = true
project_auto_root = false

# autocomplete_method = 'neocomplete' # nie dziala
# autocomplete_method = 'neocomplcache'  # dziala
# autocomplete_method = 'neocomplete' # nie dziala
# autocomplete_method = 'deoplete' nie dziala
# autocomplete_method = 'coc' dziwnie dziala
# autocomplete_method = 'YouCompleteMe' nie działa
autocomplete_method = 'completor' # działa
# autocomplete_method = 'asyncomplete' słabo działa
# snippet_engine = 'neosnippet' # default
# snippet_engine = 'ultisnips'

[[layers]]
# enabled by default
name = 'autocomplete'
auto_completion_return_key_behavior = 'smart'
auto_completion_tab_key_behavior = 'smart'

[[layers]]
# enabled by default
name = 'checkers'
# show_cursor_error = false

[[layers]]
name = 'foldsearch'

[[layers]]
# enabled by default
name = 'format'

[[layers]]
# enabled by default
name = 'edit'
autosave_timeout = 300000

[[layers]]
# enabled by default
name = 'ui'
enable_cursorword = true
enable_indentline = false
enable_scrollbar = false
enable_sidebar = true

[[layers]]
# enabled by default
name = 'core'
enable_filetree_filetypeicon = true
enable_filetree_gitstatus = true
enable_smooth_scrolling = false
filetree_show_hidden = true

[[layers]]
# enabled by default
name = 'core#statusline'

[[layers]]
# enabled by default
name = 'core#banner'

[[layers]]
# enabled by default
name = 'core#tabline'

[[layers]]
name = 'cscope'

# [[layers]]
# name = "default"

[[layers]]
name = 'foldsearch'

[[layers]]
name = 'shell'
default_height = 30
default_position = 'bottom'

[[layers]]
name = 'git'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'github'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#json'

# breaks md
# [[layers]]
#   name = 'lang#markdown'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#perl'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'denite'

[[layers]]
name = 'colorscheme'

[[custom_plugins]]
repo = 'https://github.com/lilydjwg/colorizer'

[[custom_plugins]]
repo = 'https://github.com/editorconfig/editorconfig-vim'

[[custom_plugins]]
repo = 'https://github.com/xu-cheng/brew.vim'

[[custom_plugins]]
repo = 'https://github.com/vimwiki/vimwiki'

[[custom_plugins]]
repo = 'https://github.com/godlygeek/tabular'

[[custom_plugins]]
repo = 'https://github.com/AndrewRadev/splitjoin.vim'

[[custom_plugins]]
repo = 'https://github.com/matze/vim-move'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/FavMenu.vim'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/FavEx'

[[custom_plugins]]
repo = 'https://github.com/rhysd/vim-healthcheck'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/groovy.vim'

[[custom_plugins]]
repo = 'https://github.com/wfxr/minimap.vim'

[[custom_plugins]]
repo = 'https://github.com/hashivim/vim-terraform'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/bash-support.vim'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/bats.vim'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/taglist.vim'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/betterga'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-abolish'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-scriptease'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-sensible'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-speeddating'

[[custom_plugins]]
repo = 'https://github.com/simnalamburt/vim-mundo'

[[custom_plugins]]
repo = 'https://github.com/tiagofumo/vim-nerdtree-syntax-highlight'

[[custom_plugins]]
repo = 'https://github.com/dracorp/vim-pkgbuild'

# [[custom_plugins]]
# repo = 'https://github.com/liuchengxu/vista.vim'

[[custom_plugins]]
repo = 'https://github.com/scrooloose/syntastic'

[[custom_plugins]]
repo = 'https://github.com/airblade/vim-gitgutter'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-fugitive'

[[custom_plugins]]
repo = 'https://github.com/junegunn/gv.vim'

# [[custom_plugins]]
# repo = 'https://github.com/sheerun/vim-polyglot'

[[custom_plugins]]
repo = 'https://github.com/osyo-manga/vim-over'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/DrawIt'
on_cmd = ['DrawIt']

[[custom_plugins]]
repo = 'https://github.com/honza/vim-snippets'

[[custom_plugins]]
repo = 'https://github.com/mzlogin/vim-markdown-toc'

# [[custom_plugins]]
#   repo = 'https://github.com/xolox/vim-misc'
# [[custom_plugins]]
#   repo = 'https://github.com/xolox/vim-easytags'

[[custom_plugins]]
repo = 'https://github.com/ryanoasis/vim-devicons'
