# =============================================================================
# URL: https://spacevim.org
# License: GPLv3
# =============================================================================

[options] #{{{
automatic_update = true
statusline_separator = 'arrow'
statusline_iseparator = 'bar'
statusline_left = [
  'winnr',
  'filename',
  'major mode',
  'minor mode lighters',
  'version control info',
  'search status'
]
statusline_right = [
  'fileformat',
  'cursorpos',
  'percentage',
  'whitespace',
  'syntax checking'
]
# right sections of statusline
# disable 'q' to close current window
# windows_smartclose = ''
# in vimcompatible mode, all the differences above will disappear
# windows_leader = 's'
vimcompatible = false
buffer_index_type = 0
colorscheme = 'gruvbox'
colorscheme_bg = 'dark'
default_indent = 4
disabled_plugins = ['tagbar']
enable_guicolors = true
enable_statusline_mode = true
enable_tabline_filetype_icon = true
# default is vimfiler
filemanager = 'nerdtree'
# works only in nvim
# filemanager = 'defx'
# enable_vimfiler_gitstatus = true
filetree_direction = "left"
enable_vimfiler_welcome = true
guifont = 'AgaveNF-Regular:h15'

# ~/.SpaceVim.d/autoload/myspacevim.vim
bootstrap_after = 'myspacevim#after'
bootstrap_before = 'myspacevim#before'

# options for non-project files/directories
project_non_root = 'current'
# project_rooter_patterns = ['.git/', '!node_packages/']
# project_rooter_outermost = true
# project_auto_root = false

# autocomplete_method = 'neocomplete' # nie dziala
# autocomplete_method = 'neocomplcache'  # dziala
# autocomplete_method = 'neocomplete' # nie dziala
# autocomplete_method = 'deoplete' nie dziala
# autocomplete_method = 'coc' dziwnie dziala
# autocomplete_method = 'YouCompleteMe' nie działa
autocomplete_method = 'completor' # działa
# autocomplete_method = 'asyncomplete' słabo działa
# snippet_engine = 'neosnippet' # default
# snippet_engine = 'ultisnips'

# checkers
# lint_engine = 'ale'
# lint_engine = 'syntastic'
lint_on_the_fly = true
# open_error_list = 2
#}}}

#{{{ layers
[[layers]]
# https://spacevim.org/layers/autocomplete/
# enabled by default
name = 'autocomplete'
auto_completion_return_key_behavior = 'smart'
auto_completion_tab_key_behavior = 'smart'

[[layers]]
# enabled by default
# https://spacevim.org/layers/checkers/
name = 'checkers'
show_cursor_error = true

[[layers]]
# https://spacevim.org/layers/colorscheme/
name = 'colorscheme'

[[layers]]
# https://spacevim.org/layers/core/banner/
# enabled by default
name = 'core#banner'

[[layers]]
# disabled by default
name = 'core#statuscolumn'
enable = true

[[layers]]
# https://spacevim.org/layers/core/statusline/
# enabled by default
name = 'core#statusline'
major_mode_cache = false

[[layers]]
# https://spacevim.org/layers/core/tabline/
# enabled by default
name = 'core#tabline'

[[layers]]
# https://spacevim.org/layers/core/
# enabled by default
name = 'core'
enable_filetree_filetypeicon = true
enable_filetree_gitstatus = true
enable_smooth_scrolling = false
filetree_show_hidden = true

[[layers]]
# https://spacevim.org/layers/cscope/
name = 'cscope'

[[layers]]
# https://spacevim.org/layers/ctrlspace/
name = "ctrlspace"
enable-spacevim-styled-keys = true

# [[layers]]
# https://spacevim.org/layers/debug/
# name = "debug"
# debugger_plugin = "vimspector"

[[layers]]
# https://spacevim.org/layers/default/
name = "default"

[[layers]]
# https://spacevim.org/layers/edit/
# enabled by default
name = 'edit'
autosave_timeout = 300000

[[layers]]
# https://spacevim.org/layers/foldsearch/
name = 'foldsearch'

[[layers]]
# enabled by default
# https://spacevim.org/layers/format/
name = 'format'

[[layers]]
# https://spacevim.org/layers/git/
name = 'git'

[[layers]]
# https://spacevim.org/layers/github/
name = 'github'

[[layers]]
# https://spacevim.org/layers/gtags/
name = 'gtags'
# gtagslabel = 'ctags'
gtagslabel = 'exuberant ctags'
# gtagslabel = 'pygments'

[[layers]]
name = 'incsearch'

#{{{2 langs
[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = "lang#groovy"

[[layers]]
name = 'lang#html'

# [[layers]]
# breaks md
#   name = 'lang#markdown'

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lang#perl'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#vim'

[[layers]]
name = "lang#xml"

#}}}2

[[layers]]
# https://spacevim.org/layers/language-server-protocol/
name = "lsp"

[[layers]]
# https://spacevim.org/layers/shell/
name = 'shell'
default_height = 30
default_position = 'bottom'

[[layers]]
# https://spacevim.org/layers/sudo/
name = "sudo"

[[layers]]
# https://spacevim.org/layers/tools/
name = "tools"

[[layers]]
# https://spacevim.org/layers/ui/
# enabled by default
name = 'ui'
enable_cursorword = true
enable_indentline = false
enable_scrollbar = false
enable_sidebar = true

[[layers]]
# https://spacevim.org/layers/unite/
name = 'unite'

[[layers]]
# https://spacevim.org/layers/VersionControl/
name = 'VersionControl'
#}}}

#{{{ custom plugins
[[custom_plugins]]
repo = 'https://github.com/lilydjwg/colorizer'

[[custom_plugins]]
repo = 'https://github.com/editorconfig/editorconfig-vim'

[[custom_plugins]]
repo = 'https://github.com/xu-cheng/brew.vim'

[[custom_plugins]]
repo = 'https://github.com/vimwiki/vimwiki'

[[custom_plugins]]
repo = 'https://github.com/godlygeek/tabular'

[[custom_plugins]]
repo = 'https://github.com/AndrewRadev/splitjoin.vim'

[[custom_plugins]]
repo = 'https://github.com/matze/vim-move'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/FavMenu.vim'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/FavEx'

[[custom_plugins]]
repo = 'https://github.com/rhysd/vim-healthcheck'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/groovy.vim'

[[custom_plugins]]
repo = 'https://github.com/wfxr/minimap.vim'

[[custom_plugins]]
repo = 'https://github.com/hashivim/vim-terraform'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/bash-support.vim'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/bats.vim'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/taglist.vim'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/betterga'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-abolish'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-scriptease'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-sensible'

# [[custom_plugins]]
# repo = 'https://github.com/tpope/vim-speeddating'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-repeat'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-fugitive'

[[custom_plugins]]
repo = 'https://github.com/tpope/vim-rhubarb'

[[custom_plugins]]
repo = 'https://github.com/rhysd/committia.vim'

[[custom_plugins]]
repo = 'https://github.com/simnalamburt/vim-mundo'

[[custom_plugins]]
repo = 'https://github.com/tiagofumo/vim-nerdtree-syntax-highlight'

[[custom_plugins]]
repo = 'https://github.com/dracorp/vim-pkgbuild'

[[custom_plugins]]
repo = 'https://github.com/liuchengxu/vista.vim'

[[custom_plugins]]
repo = 'https://github.com/scrooloose/syntastic'

[[custom_plugins]]
repo = 'https://github.com/airblade/vim-gitgutter'

[[custom_plugins]]
repo = 'https://github.com/junegunn/gv.vim'

# [[custom_plugins]]
# repo = 'https://github.com/sheerun/vim-polyglot'

[[custom_plugins]]
# :substitute preview
repo = 'https://github.com/osyo-manga/vim-over'

[[custom_plugins]]
repo = 'https://github.com/vim-scripts/DrawIt'
on_cmd = ['DrawIt']

[[custom_plugins]]
repo = 'https://github.com/honza/vim-snippets'

[[custom_plugins]]
repo = 'https://github.com/mzlogin/vim-markdown-toc'

# [[custom_plugins]]
# repo = 'https://github.com/instant-markdown/vim-instant-markdown'

# [[custom_plugins]]
#   repo = 'https://github.com/xolox/vim-misc'
# [[custom_plugins]]
#   repo = 'https://github.com/xolox/vim-easytags'

[[custom_plugins]]
repo = 'https://github.com/ryanoasis/vim-devicons'

# [[custom_plugins]]
# repo = 'https://github.com/khzaw/vim-conceal'

# [[custom_plugins]]
# repo = 'https://github.com/Shougo/vimproc.vim'

[[custom_plugins]]
repo = 'https://github.com/mg979/vim-visual-multi'

# [[custom_plugins]]
# repo = 'https://github.com/wellle/context.vim'

# [[custom_plugins]]
# repo = 'https://github.com/Shougo/echodoc.vim'

[[custom_plugins]]
repo = 'https://github.com/itchyny/calendar.vim'
#}}}

