# =============================================================================
# URL: https://spacevim.org
# License: GPLv3
# =============================================================================

[options] #{{{
# automatic_update = true
# statusline_separator = 'arrow'
# statusline_iseparator = 'bar'
statusline_left = [
  'winnr',
  'filename',
  'major mode',
  'minor mode lighters',
  'version control info',
  'search status'
]
statusline_right = [
  'fileformat',
  'cursorpos',
  'percentage',
  'whitespace',
  'syntax checking'
]
# disable 'q' to close current window
# windows_smartclose = ''
# in vimcompatible mode, all the differences above will disappear
# windows_leader = 's'
vimcompatible = false
# buffer_index_type = 0
# colorscheme = 'gruvbox'
# colorscheme_bg = 'dark'
# default_indent = 4
disabled_plugins = ['splitjoin.vim']
enable_guicolors = 1
# enable_statusline_mode = true
# enable_tabline_filetype_icon = true
# default is nerdtree
filemanager = 'nerdtree'
# filemanager = 'vimfiler'
# works only in nvim
# filemanager = 'defx'
# enable_vimfiler_gitstatus = true
filetree_direction = 'left'
# enable_vimfiler_welcome = true
guifont = 'AgaveNF-Regular:h15'
escape_key_binding = ''
relativenumber = false

# options for non-project files/directories
project_non_root = 'current'
# project_rooter_patterns = ['.git/', '!node_packages/']
# project_rooter_outermost = 1
project_auto_root = false

# Default
# autocomplete_method = 'asyncomplete' # słabo działa
# asyncomplete-buffer.vim
# asyncomplete-necovim.vim
# asyncomplete-omni.vim
# asyncomplete.vim

# autocomplete_method = 'neocomplete' # nie dziala

# autocomplete_method = 'neocomplcache'  # dziala ale nie do końca
# neocomplcache.vim

# autocomplete_method = 'deoplete' # dziala ale nie do końca

# autocomplete_method = 'coc' # dziala
# coc-neco

# autocomplete_method = 'YouCompleteMe' # nie działa

# autocomplete_method = 'completor' # działa
# echodoc.vim
# completor-neosnippet
# completor.vim

# snippet_engine = 'neosnippet' # default
# snippet_engine = 'ultisnips'

# checkers, default neomake
# lint_engine = 'neomake'
# lint_engine = 'ale'
lint_engine = 'syntastic'

# enable_googlesuggest = 1
# vim_help_language = 'pl'

# ~/.SpaceVim.d/autoload/myspacevim.vim
bootstrap_before = 'myspacevim#before'
bootstrap_after = 'myspacevim#after'
#}}}

#{{{ layers
# https://spacevim.org/layers/autocomplete/
# enabled by default
# [[layers]]
# name = 'autocomplete'
# auto_completion_return_key_behavior = 'smart'
# auto_completion_tab_key_behavior = 'smart'

# enabled by default
# https://spacevim.org/layers/checkers/
[[layers]]
name = 'checkers'
show_cursor_error = false
lint_on_the_fly = true
open_error_list = 0

# [[layers]]
# name = 'colorscheme'
# NeoSolarized
# jellybeans.vim
# molokai
# nord-vim
# onedark.vim
# palenight.vim
# srcery-vim
# vim-hybrid
# vim-material

# https://spacevim.org/layers/core/banner/
# enabled by default
# [[layers]]
# name = 'core#banner'

# disabled by default
# [[layers]]
# name = 'core#statuscolumn'

# https://spacevim.org/layers/core/statusline/
# enabled by default
# [[layers]]
# name = 'core#statusline'
# major_mode_cache = false

# https://spacevim.org/layers/core/tabline/
# enabled by default
# [[layers]]
# name = 'core#tabline'

# https://spacevim.org/layers/core/
# enabled by default
[[layers]]
name = 'core'
enable_filetree_filetypeicon = true
enable_filetree_gitstatus = true
enable_smooth_scrolling = false
filetree_show_hidden = true

# https://spacevim.org/layers/cscope/
# [[layers]]
# name = 'cscope'
# auto_update = 1
# open_location = 1

# https://spacevim.org/layers/ctrlp/
# https://spacevim.org/documentation/#fuzzy-finder
# [[layers]]
# name = 'ctrlp'
# ctrlp-jumps
# ctrlp-menu
# ctrlp-py-matcher
# ctrlp-register
# ctrlp-yank
# ctrlp.vim
# vim-ctrlp-help
# vim-ctrlp-message

# https://spacevim.org/layers/ctrlspace/
# vim-ctrlspace
# [[layers]]
# name = 'ctrlspace'
# enable-spacevim-styled-keys = true

# https://spacevim.org/layers/debug/
# vim-debug
# vimproc.vim
# [[layers]]
# name = 'debug'
# debugger_plugin = 'vimspector'

# https://spacevim.org/layers/default/
# [[layers]]
# name = 'default'

# https://spacevim.org/layers/denite/
# https://spacevim.org/documentation/#fuzzy-finder
# Denite-sources
# denite-gtags
# denite.nvim
# unite-location
# unite-outline
# vim-denite-emoji
# [[layers]]
# name = 'denite'

# https://spacevim.org/layers/edit/
# enabled by default
# [[layers]]
# name = 'edit'
# autosave_timeout = 300000

# https://spacevim.org/layers/foldsearch/
# [[layers]]
# name = 'foldsearch'

# enabled by default
# https://spacevim.org/layers/format/
# [[layers]]
# name = 'format'

# https://spacevim.org/layers/fzf/
# https://spacevim.org/documentation/#fuzzy-finder
# fzf
# fzf-neoyank
# [[layers]]
# name = 'fzf'

# [[layers]] # broken
# name = 'fuzzy'

# https://spacevim.org/layers/git/
# vim-gitgutter
[[layers]]
name = 'git'

# https://spacevim.org/layers/github/
# open-browser-github.vim
# vim-gista
# [[layers]]
# name = 'github'

# [SPC g 2]
# [[layers]]
# enable = true
# name = 'games'

# https://spacevim.org/layers/gtags/
[[layers]]
name = 'gtags'
gtagslabel = 'ctags'
# gtagslabel = 'exuberant ctags'
auto_update = true
open_quickfix = 1
# gtagslabel = 'pygments'

[[layers]]
name = 'incsearch'

#{{{2 langs
# vim-dockerfile
[[layers]]
name = 'lang#dockerfile'

# groovy.vim
[[layers]]
name = 'lang#groovy'

# emmet-vim
# html5.vim
# scss-syntax.vim
# vim-css-color
# vim-css3-syntax
# vim-less
# vim-stylus
[[layers]]
name = 'lang#html'

# [[layers]]
# breaks md
#   name = 'lang#markdown'

# json5.vim
# vim-json
[[layers]]
name = 'lang#json'

# perldoc-vim
# perlomni.vim
# vim-perl
[[layers]]
name = 'lang#perl'

# vim-pydocstring
[[layers]]
name = 'lang#python'

# deoplete-zsh
# vim-fish
# vim-zsh
# [[layers]]
# name = 'lang#sh'

[[layers]]
name = 'lang#toml'

# exception.vim
# neco-vim
# vim-vimlint
# vim-vimlparser
# vint-syntastic
[[layers]]
name = 'lang#vim'

# MatchTagAlways
# xmledit
# [[layers]]
# name = 'lang#xml'

#}}}2

# https://spacevim.org/layers/language-server-protocol/
# async.vim
# vim-lsp
# [[layers]]
# name = 'lsp'

# https://spacevim.org/layers/shell/
# Spc '
# vimshell.vim
[[layers]]
name = 'shell'
default_height = 30
default_position = 'bottom'

# https://spacevim.org/layers/sudo/
# [[layers]]
# name = 'sudo'

# https://spacevim.org/layers/tools/
# Mysql.vim
# VimCalc3
# fencview
# goyo.vim
# limelight.vim
# vim-scriptease
# vimloo
# vnote
[[layers]]
name = 'tools'

[[layers]]
# https://spacevim.org/layers/ui/
# enabled by default
name = 'ui'
enable_cursorword = true
enable_indentline = true
indentline_char = '⦙'
conceallevel = 0
concealcursor = ''
enable_scrollbar = false
enable_sidebar = true

# https://spacevim.org/layers/unite/
# https://spacevim.org/documentation/#fuzzy-finder
# unite-outline
# unite-quickfix
# [[layers]]
# name = 'unite'

# https://spacevim.org/layers/VersionControl/
[[layers]]
name = 'VersionControl'

# vim-terminal
# [[layers]]
# name = 'vim'
#}}}

#{{{ custom plugins
[[custom_plugins]]
# A Vim plugin to colorize all text in the form #rrggbb or #rgb.
repo = 'https://github.com/lilydjwg/colorizer'

# 🍺 Vim Syntax for Homebrew formulae
[[custom_plugins]]
repo = 'https://github.com/xu-cheng/brew.vim'

# Personal Wiki for Vim
[[custom_plugins]]
repo = 'https://github.com/vimwiki/vimwiki'

# Plugin to move lines and selections up and down
# [[custom_plugins]]
# repo = 'https://github.com/matze/vim-move'

# A new menu, like IE's Favourites, or Netscape's Bookmark
[[custom_plugins]]
repo = 'https://github.com/vim-scripts/FavMenu.vim'

# Favorite file and directory explorer
[[custom_plugins]]
repo = 'https://github.com/vim-scripts/FavEx'

# Switch between single-line and multiline forms of code
[[custom_plugins]] # built-in edit but broken
repo = 'https://github.com/AndrewRadev/splitjoin.vim'
merged = false

# 📡 Blazing fast minimap / scrollbar for vim, powered by code-minimap written in Rust.
# [[custom_plugins]]
# repo = 'https://github.com/wfxr/minimap.vim'

# basic vim/terraform integration
# [[custom_plugins]]
# repo = 'https://github.com/hashivim/vim-terraform'

# BASH IDE -- Write and run BASH-scripts using menus and hotkeys.
[[custom_plugins]]
repo = 'https://github.com/vim-scripts/bash-support.vim'

# Syntax highlighting for Bats - Bash Automated Testing System
# [[custom_plugins]]
# repo = 'https://github.com/vim-scripts/bats.vim'

# Source code browser (supports C/C++, java, perl, python, tcl, sql, php, etc)
[[custom_plugins]]
repo = 'https://github.com/vim-scripts/taglist.vim'

# Yet another :ascii command
[[custom_plugins]]
repo = 'https://github.com/vim-scripts/betterga'
# on_func = 'betterga#ascii'

# abolish.vim: Work with several variants of a word at once
# [[custom_plugins]]
# repo = 'https://github.com/tpope/vim-abolish'

# sensible.vim: Defaults everyone can agree on
# [[custom_plugins]]
# repo = 'https://github.com/tpope/vim-sensible'

# use CTRL-A/CTRL-X to increment dates, times, and more
# [[custom_plugins]]
# repo = 'https://github.com/tpope/vim-speeddating'

# A Git wrapper so awesome, it should be illegal
[[custom_plugins]]
repo = 'https://github.com/tpope/vim-fugitive'

# GitHub extension for fugitive.vim
# [[custom_plugins]]
# repo = 'https://github.com/tpope/vim-rhubarb'

# A Vim plugin for more pleasant editing on commit messages
[[custom_plugins]]
repo = 'https://github.com/rhysd/committia.vim'

# Extra syntax and highlight for nerdtree files
# requires vim-devicons
# [[custom_plugins]]
# repo = 'https://github.com/tiagofumo/vim-nerdtree-syntax-highlight'

# easy work with ArchLinux PKGBUILD
[[custom_plugins]]
repo = 'https://github.com/dracorp/vim-pkgbuild'

# 🌵 Viewer & Finder for LSP symbols and tags
[[custom_plugins]]
repo = 'https://github.com/liuchengxu/vista.vim'

#  Syntax checking hacks for vim
[[custom_plugins]]
repo = 'https://github.com/scrooloose/syntastic'
# on_cmd = ['SyntasticCheck', 'SyntasticInfo']

[[custom_plugins]]
repo = 'https://github.com/itspriddle/vim-shellcheck'
on_cmd = ['ShellCheck', 'LShellCheck']

# A git commit browser in Vim
[[custom_plugins]]
repo = 'https://github.com/junegunn/gv.vim'
on_cmd = ['GV']

# Ascii drawing plugin: lines, ellipses, arrows, fills, and more!
[[custom_plugins]]
repo = 'https://github.com/vim-scripts/DrawIt'
on_cmd = ['DrawIt']

# vim-snipmate default snippets (Previously snipmate-snippets)
[[custom_plugins]]
repo = 'https://github.com/honza/vim-snippets'

# A vim 7.4+ plugin to generate table of contents for Markdown files.
[[custom_plugins]]
repo = 'https://github.com/mzlogin/vim-markdown-toc'
on_cmd = ['GenTocGFM', 'GenTocRedcarpet', 'GenTocGitLab', 'GenTocMarked', 'UpdateToc', 'RemoveToc' ]

# A calendar application for Vim
[[custom_plugins]] # built-in tools but Calendar is not available
repo = 'https://github.com/itchyny/calendar.vim'
on_cmd = ['Calendar']

# Miscellaneous auto-load Vim scripts
[[custom_plugins]]
repo = 'https://github.com/xolox/vim-misc'

# Automated tag file generation and syntax highlighting of tags in Vim
# [[custom_plugins]]
# repo = 'https://github.com/xolox/vim-easytags'

# [[custom_plugins]]
# repo = 'https://github.com/xolox/vim-colorscheme-switcher'

[[custom_plugins]]
repo = 'https://github.com/Donaldttt/fuzzyy'

[[custom_plugins]]
repo = 'https://github.com/vim-utils/vim-man'
on_cmd = ['Man', 'Vman']

# [[custom_plugins]]
# repo = 'https://github.com/chrisbra/csv.vim'

# [[custom_plugins]]
# repo = 'https://github.com/Yggdroot/indentLine'

# [[custom_plugins]]
# repo = 'https://github.com/vim-airline/vim-airline'
# [[custom_plugins]]
# repo = 'https://github.com/vim-airline/vim-airline-themes'

[[custom_plugins]]
repo = 'https://github.com/pedrohdz/vim-yaml-folds'

# Adds file type icons to Vim plugins such as: NERDTree, vim-airline, CtrlP, unite, Denite, lightline, vim-startify and many more
[[custom_plugins]]
repo = 'https://github.com/ryanoasis/vim-devicons'

#[[custom_plugins]]
#repo = 'https://github.com/preservim/nerdcommenter'
# Disabled plugins {{{
# [[custom_plugins]]
# A solid language pack for Vim
# repo = 'https://github.com/sheerun/vim-polyglot'

# [[custom_plugins]]
# Instant Markdown previews from Vim
# repo = 'https://github.com/instant-markdown/vim-instant-markdown'

# [[custom_plugins]]
# Vim plugin that shows the context of the currently visible buffer contents
# repo = 'https://github.com/wellle/context.vim'

# [[custom_plugins]]
# Print documents in echo area
# repo = 'https://github.com/Shougo/echodoc.vim'

# }}}
# Disabled plugins built-in {{{
# [[custom_plugins]] # built-in groovy
# syntax file for the groovy programming language
# repo = 'https://github.com/vim-scripts/groovy.vim'

# [[custom_plugins]] # built-in tools
# scriptease.vim: A Vim plugin for Vim plugins
# repo = 'https://github.com/tpope/vim-scriptease'

# [[custom_plugins]] # built-in core
# Interactive command execution in Vim.
# repo = 'https://github.com/Shougo/vimproc.vim'

# [[custom_plugins]] # built-in editor
# EditorConfig plugin for Vim
# repo = 'https://github.com/editorconfig/editorconfig-vim'

# [[custom_plugins]] # built-in editor
# Vim script for text filtering and alignment
# repo = 'https://github.com/godlygeek/tabular'

# [[custom_plugins]] # built-in editor
# enable repeating supported plugin maps with "."
# repo = 'https://github.com/tpope/vim-repeat'

# [[custom_plugins]] # built-in edit
# 🎄 Vim undo tree visualizer
# repo = 'https://github.com/simnalamburt/vim-mundo'

# [[custom_plugins]] # built-in incsearch
# :substitute preview
# repo = 'https://github.com/osyo-manga/vim-over'
# }}}
#}}}
