#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arror"
    buffer_index_type = 4
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = true
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    enable_statusline_mode = true
    filemanager = "nerdtree"
    bootstrap_before = "myspacevim#before"
    bootstrap_before = "myspacevim#after"
    # ~/.SpaceVim.d/autoload/myspacevim.vim
    # disable 'q' to close current window
    # windows_smartclose = ''
    # in vimcompatible mode, all the differences above will disappear
    vimcompatible = true
    # disabled_plugins = ["neomake.vim",]
    guifont = "AgaveNF-Regular:h15"
    automatic_update = true
    default_indent = 4

#    autocomplete_method = "deoplete"
    snippet_engine = "ultisnips"

[[layers]]
    name = 'core'
    filetree_show_hidden = true
    enable_filetree_filetypeicon = true
    enable_filetree_gitstatus = true
    enable_smooth_scrolling = true

[[layers]]
    name = "default"

[[layers]]
    name = "foldsearch"

[[layers]]
    name = "checkers"
    show_cursor_error = false

[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "smart"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = "ui"
    enable_scrollbar = true
    enable_sidebar = true
    enable_cursorword = true
    indentline_char = '|'

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = "core#statusline"

[[layers]]
    name = 'git'

[[layers]]
    name = "github"

[[layers]]
    name = "lang#dockerfile"

[[layers]]
    name = "lang#html"

[[layers]]
    name = "lang#json"

[[layers]]
    name = "lang#markdown"

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#perl"
    enable = false

[[layers]]
    name = "lang#sh"

[[layers]]
    name = "lang#vim"

[[custom_plugins]]
    repo = "https://github.com/lilydjwg/colorizer"

[[custom_plugins]]
    repo = "https://github.com/tpope/vim-commentary"

[[custom_plugins]]
    repo = "https://github.com/scrooloose/nerdcommenter"

[[custom_plugins]]
    repo = "https://github.com/tpope/vim-abolish"

[[custom_plugins]]
    repo = "https://github.com/editorconfig/editorconfig-vim"

[[custom_plugins]]
    repo = "https://github.com/xu-cheng/brew.vim"

[[custom_plugins]]
    repo = "https://github.com/vimwiki/vimwiki"

[[custom_plugins]]
    repo = "https://github.com/godlygeek/tabular"

[[custom_plugins]]
    repo = "https://github.com/AndrewRadev/splitjoin.vim"

[[custom_plugins]]
    repo = "https://github.com/matze/vim-move"

[[custom_plugins]]
    repo = 'https://github.com/vim-scripts/FavMenu.vim'
[[custom_plugins]]
    repo = 'https://github.com/vim-scripts/FavEx'
[[custom_plugins]]
    repo = 'https://github.com/rhysd/vim-healthcheck'
[[custom_plugins]]
    repo = 'https://github.com/vim-scripts/groovy.vim'
[[custom_plugins]]
    repo = 'https://github.com/wfxr/minimap.vim'
[[custom_plugins]]
    repo = 'https://github.com/hashivim/vim-terraform'
